language: python

python:
  - "3.6"
  
  
install:
  - pip install -r requirements.txt  

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test_questioner;" -U postgres
  - psql -c "CREATE DATABASE questioner;" -U postgres
  
script:
  - pytest --cov=app
  
  
after_success:
  - coveralls

